# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(email: "hungrygames@penang.com", password: "12345678")

Image.create(image_location: "Penang",image_title: "Char Koay Teow", image_url: "http://farm4.static.flickr.com/3406/4639234240_1573b9497d_o.jpg")
Image.create(image_location: "Penang",image_title: "Char Koay Kak", image_url: "http://farm5.static.flickr.com/4037/4634781827_a2130bae1f_o.jpg")
Image.create(image_location: "Penang",image_title: "Hokkien Mee",image_url: "http://www.chasechin.com/wp-content/uploads/2013/05/888HokkienMee-021.jpg")
Image.create(image_location: "Penang",image_title: "Curry Mee",image_url: "http://1.bp.blogspot.com/-HsjUo7tzG7g/UHGS2oVbnMI/AAAAAAAAAPg/XPwilxOb6JE/s1600/P1160045.jpg")
Image.create(image_location: "Penang",image_title: "Lou Mai Kai",image_url: "http://www.what2seeonline.com/wp-content/uploads/2011/10/DPP_0596_resize_thumb.jpg")
Image.create(image_location: "Penang",image_title: "Lau Sa Pau",image_url: "http://farm8.staticflickr.com/7145/6700978249_9bd9c15ff6_o.jpg")
Image.create(image_location: "Penang",image_title: "Char Siew Pau",image_url: "http://farm5.static.flickr.com/4084/4980981660_3bacab03e6.jpg")
Image.create(image_location: "Penang",image_title: "Baked Char Siew Pau",image_url: "http://i.insing.com.sg/cms/a3/92/59/65/32146/a392596532146_600x450_fillbg_6f834d8667.jpg")
Image.create(image_location: "Penang",image_title: "Nasi Kandar",image_url: "http://static.asiawebdirect.com/m/kl/portals/penang-ws/homepage/dining/5-best-nasi-kandar/pagePropertiesImage/nasi-kandar.jpg")
Image.create(image_location: "Penang",image_title: "Roti Canai",image_url: "http://s3.amazonaws.com/foodspotting-ec2/reviews/2734086/thumb_600.jpg?1353061629")
Image.create(image_location: "Penang",image_title: "Laksa",image_url: "http://my.openrice.com/userphoto/Article/0/A/0002263DF8F46B8D222049j.jpg")
Image.create(image_location: "Penang",image_title: "Lok Lok",image_url: "https://eyriquefoodjournal.files.wordpress.com/2012/07/20120717-093947.jpg")
Image.create(image_location: "Penang",image_title: "Bak Kut Teh",image_url: "http://www.tasteiest.com/wp-content/uploads/carnationbktl94.jpg")
Image.create(image_location: "Penang",image_title: "Apom",image_url: "https://c4.staticflickr.com/8/7666/17571906116_a62d9d17bc_c.jpg")
Image.create(image_location: "Penang",image_title: "Ban Chean Kuih",image_url: "http://www.gopenang.my/site/wp-content/uploads/2013/09/Aki-Pancake.jpg")
Image.create(image_location: "Penang",image_title: "Economic Rice",image_url: "http://farm4.static.flickr.com/3093/2679310632_23d214e5f8.jpg")
Image.create(image_location: "Penang",image_title: "Oh Chien",image_url: "http://danielfooddiary.com/wp-content/uploads/2014/08/penang3.jpg")
Image.create(image_location: "Penang",image_title: "Mee Sotong",image_url: "http://kyspeaks.com/photos3/mee_sotong_padang_kota_2.jpg")
Image.create(image_location: "Penang",image_title: "Wan Tan Mee",image_url: "http://www.visitpenang.gov.my/portal3/images/stories/wantanmee.jpg")
Image.create(image_location: "Penang",image_title: "Loh Mee",image_url: "http://www.gourmetgarden.com.my/wp-content/uploads/2012/09/CameraZOOM-20120408102349123.jpg")
Image.create(image_location: "Penang",image_title: "Nasi Lemak",image_url: "http://farm3.static.flickr.com/2784/4341758451_997ffaf71d.jpg")
Image.create(image_location: "Penang",image_title: "Chendol",image_url: "http://farm6.staticflickr.com/5528/10976865095_1e6e422887_b.jpg")
Image.create(image_location: "Penang",image_title: "Satay",image_url: "https://c1.staticflickr.com/9/8486/8172158699_180e42ba31_b.jpg")
Image.create(image_location: "Penang",image_title: "Koay Chiap",image_url: "http://www.what2seeonline.com/wp-content/uploads/2009/02/photo-1.jpg")
Image.create(image_location: "Penang",image_title: "Chee Cheong Fun",image_url: "http://1.bp.blogspot.com/-6_YVXmo0r1k/TkPrBwQnyYI/AAAAAAAAB-U/Spsg8iiq8pg/s1600/Penang+food+1.jpg")
Image.create(image_location: "Penang",image_title: "Koay Teow Th'ng",image_url: "http://ak-hdl.buzzfed.com/static/2014-03/enhanced/webdr06/26/18/enhanced-27572-1395874355-5.jpg")
Image.create(image_location: "Penang",image_title: "Ais Kacang",image_url: "http://www.pulaupinang.com/wp-content/uploads/2011/03/jalil-special-ais-kacang-dish.jpg")
Image.create(image_location: "Penang",image_title: "Roti Bak Kua",image_url: "http://ak-hdl.buzzfed.com/static/2014-04/enhanced/webdr05/1/18/grid-cell-5572-1396391586-14.jpg")
Image.create(image_location: "Penang",image_title: "Chicken Rice",image_url: "http://ak-hdl.buzzfed.com/static/2014-04/enhanced/webdr08/1/18/grid-cell-16880-1396391378-5.jpg")
Image.create(image_location: "Penang",image_title: "Pasembur",image_url: "http://myselera.com/wp-content/uploads/2014/12/Pasembur-Persiaran-Gurney-4.jpg")
Image.create(image_location: "Penang",image_title: "Rojak",image_url: "http://farm4.staticflickr.com/3714/8922540535_d91362fc15_b.jpg")
Image.create(image_location: "Penang",image_title: "Mee Udang",image_url: "http://farm6.static.flickr.com/5132/5404097051_6e34f93654_b.jpg")
Image.create(image_location: "Penang",image_title: "Egg Tart",image_url: "http://www.mywisewife.com/images/stories/FoodReview/Pg_MingXiangTai/MingXiangTai3.JPG")
